name: CI/CD for Django Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_USER: test_pg_user
          POSTGRES_PASSWORD: 123456
          DATABASE_NAME: test_database
        ports:
          - 5432:5432
      redis:
        image: redis:6-alpine
        ports:
          - 6379:6379
      clickhouse:
        image: clickhouse/clickhouse-server:23.8.2.7-alpine
        ports:
          - 8123:8123
        volumes:
          - ./docker/clickhouse/init.sql:/docker-entrypoint-initdb.d/init.sql

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest pytest-django

      - name: Run tests
        run: |
          pytest --maxfail=1 --disable-warnings -q

      - name: Run database migrations
        run: |
          python manage.py migrate

      - name: Collect static files
        run: |
          python manage.py collectstatic --noinput
